### ISSUE TITLE
sugg recs

### ISSUE THREAD

**Issue by yhm-amber** [pure-symbols/pure.lexicals#1]
~~~
pure.ts/readme.md
pure.ts/pure.ts
pure.ts/teach.md
~~~

**Comment by yhm-amber** [comment]
tesch ：
​
​1. 一般函数调用到柯理化（强调形式转换和等价性而非原理）
​2. 柯理化原理（强调函数作为值返回）
3. 管道原理（简单那个）
4. 管线（你有一个容易理解的版本（应该是从管道改过去的，你最初试图做一个管线就是管道的封装，然后管道命名为管工并且更改了返回闭包的返回值：先是延迟化然后又加上了 Pair 好能够取出值来，然后你发现管工可以改成管线而管线则删掉即可。与其说 teaching 不如说是产出过程。我找找有没有更合适的名字：产出过程，而不是教述。），不在你现在的代码里，把那个可以用在 teachings 文件里。）


剩下的还有迭代器，你看着来。那个就是个特定的 Pair 而已，你知道的。

**Comment by yhm-amber** [comment]
And `Lazywarp` should be `Lacking`.

And, the pipe's end should be `.head()`, not `.head` --- it should be Lacked .

**Comment by yhm-amber** [comment]
更正点 +1 ：

不是「函数是第一类」，而是「支持词法闭包」。后者包含了前者的概念。或者，二者都提及，毕竟后者有成立的前提。

**Comment by yhm-amber** [comment]
（以及，其实是词法闭包救了你（其中包括我），而不是别的 ……）

"正是词法闭包的机制，使得延迟执行成为可能。"

**Comment by yii-iiy** [comment]
> teach.md

no teach.md

**Comment by yii-iiy** [comment]
- [x] 1
- [x] 2
- [x] 3
- [x] 4

> tesch ： ​ ​1. 一般函数调用到柯理化（强调形式转换和等价性而非原理） ​2. 柯理化原理（强调函数作为值返回） 3. 管道原理（简单那个） 4. 管线（你有一个容易理解的版本（应该是从管道改过去的，你最初试图做一个管线就是管道的封装，然后管道命名为管工并且更改了返回闭包的返回值：先是延迟化然后又加上了 Pair 好能够取出值来，然后你发现管工可以改成管线而管线则删掉即可。与其说 teaching 不如说是产出过程。我找找有没有更合适的名字：产出过程，而不是教述。），不在你现在的代码里，把那个可以用在 teachings 文件里。）
> 
> 剩下的还有迭代器，你看着来。那个就是个特定的 Pair 而已，你知道的。
